schema_version = "1.0.0"

id = "stb_section_toolbox"

version = "0.0.1"
name = "Section Toolbox"
tagline = "Parametric section box and planar cuts with SVG DXF export"
maintainer = "Victor Calixto"
type = "add-on"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

tags =["Modeling", "Mesh", "Import-Export", "3D View", "Object"] 

[permissions]
files = "Export SVG and DXF to disk"

[build]
paths_exclude_pattern = [
   "__pycache__/",
   "/.git/",
   "/*.zip",
 ]

